### ISSUE TITLE
TNTRun v1.0.0 To-Do

### ISSUE THREAD

**Issue by Flavius12** [ItalianDevs4PM/TNTRun#2]
TNTRun v1.0.0 (plugin) To-Do:
- [x] Fare una lista To-Do
- [x] Struttura base comandi
- [x] Sub cmd
  - [x] Join, Spectate
  - [x] Pos1, Pos2, Addfloor, Create
  - [x] SetArenaSpawn
  - [x] Leave, lobby
  - [x] Cmds, About
  - [x] setmoneyrewards
  - [x] setminandmax of players
- [x] Arene
  - [x] Handlers
    - [x] GameHandler
    - [x] PlayerHandler
  - [x] Managers
- [x] Stats Saving
  - [x] Classi e interfacce
  - [x] Applicarle al gioco
- [x] tasks
- [x] Economy
  - [x] MassiveEconomy
  - [x] PocketMoney
  - [x] Economys
- [x] Implemetare l'economy con le statistiche
- [x] CustomMessages (With translation service) (uscite la classe di AdvancedKits --luca)
- [x] EventListener
- [x] Cartelli
  - [x] JoinGame
- [x] Per le cose già fatte usate questo markdown

TNTRun v1.0.0 (webstats) To-Do:
- [x] Supporto MySQL
- [ ] Supporto Sqlite3

**Comment by Pluginer-al3rb** [comment]
Plz link is plugin download

**Comment by luca28pet** [comment]
@Pluginer-al3rb plz read the readme

**Comment by thelucyclub** [comment]
It looks like its done. Is it? It says it isn't.

**Comment by NyaomiDEV** [comment]
@thelucyclub We don't develop plugins anymore. It is unfinished

**Comment by thelucyclub** [comment]
oh. also that was fast xD

**Comment by NyaomiDEV** [comment]
@thelucyclub Ikr

**Comment by thelucyclub** [comment]
thx
